#####################################################
# Get features
#####################################################
get_pytorch_features: False
data_dir:
  - 'Z:/storage/Code/7720/project/data/tigers/'
  - 'Z:/storage/Code/7720/project/data/cheetahs/'
  # - 'Z:/storage/Code/7720/project/data/monkeys/'
features_dir:
  - 'Z:/storage/Code/7720/project/data/tiger_features'
  - 'Z:/storage/Code/7720/project/data/cheetah_features'
  # - 'Z:/storage/Code/7720/project/data/monkey_features'

  
#####################################################
# Dimensional Reduction
#####################################################
# 'pca', 'lda', 'qda'
dim_red_choice: 'pca'
projection_dim: 3
display_projection: True


#####################################################
# 
#####################################################